version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 8000:5000
    env_file:
      - ./.env.dev
  db:
    image: postgres:13-alpine
    # Enables the persistence of the data in postgres
    # Local machine has a volume where the postgresql container writes to ...?
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data:  